import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          
          {/* Sidebar */}
          <div className="w-64 bg-gray-900 text-white p-6 space-y-6">
            <h1 className="text-xl font-bold">VC Intelligence</h1>
            <input
              type="text"
              placeholder="Global search..."
              className="p-2 rounded text-black w-full mb-4"
              />
            <nav className="flex flex-col space-y-3">
              <Link href="/companies" className="hover:text-gray-300">
                Companies
              </Link>
              <Link href="/lists" className="hover:text-gray-300">
                Lists
              </Link>
            </nav>
          </div>

          {/* Main Content */}
          <div className="flex-1 p-8 bg-gray-50">
            {children}
          </div>

        </div>
      </body>
    </html>
  )
}
